apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://192.168.1.33
  name: development
contexts:
- context:
    cluster: development
    namespace: development
    user: developer
  name: development
current-context: development
kind: Config
preferences: {}
users:
- name: developer
  user:
    password: dev
    username: dev
